export {
  VideoPlayer,
  Video,
  VideoControls,
  VideoBar,
  VideoPlayButton,
  VideoSeek,
  VideoTime,
  VideoVolume,
  VideoFullscreen,
  VideoSpinner,
  videoPlayerVariants,
  type VideoPlayerProps,
  type VideoProps,
  type VideoPlayButtonProps,
  type VideoSeekProps,
  type VideoVolumeProps,
  type VideoFullscreenProps,
} from "./video-player"
