export {
  LoginForm,
  SignUpForm,
  ProviderForm,
  authFormVariants,
  type LoginFormProps,
  type LoginFormData,
  type SignUpFormProps,
  type SignUpFormData,
  type ProviderFormProps,
  type SocialLink,
  type SocialNetwork,
  type AuthProvider,
  type AuthFormLabels,
} from "./auth-form"
