export {
  TableOfContents,
  TableOfContentsTitle,
  TableOfContentsList,
  TableOfContentsItem,
  useScrollSpy,
  useHeadings,
  tableOfContentsVariants,
  type TableOfContentsProps,
  type TableOfContentsTitleProps,
  type TableOfContentsItemProps,
  type TableOfContentsHeading,
  type TableOfContentsLevel,
  type UseScrollSpyOptions,
} from "./table-of-contents"
