export {
  navigationMenuVariants,
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuTrigger,
  NavigationMenuContent,
  NavigationMenuLink,
  NavigationMenuLinkText,
  NavigationMenuLinkDescription,
  NavigationMenuLinkIcon,
  NavigationMenuLinkMedia,
  NavigationMenuGroup,
  NavigationMenuGroupLabel,
  NavigationMenuFooter,
  NavigationMenuSub,
  NavigationMenuSubViewport,
  NavigationMenuIndicator,
  NavigationMenuViewport,
  type NavigationMenuProps,
  type NavigationMenuContentProps,
  type NavigationMenuLinkProps,
  type NavigationMenuSubProps,
} from "./navigation-menu"
