/**
 * Emoji dataset for EmojiPicker: plain data, no React, no icons (the nav maps category
 * ids to Phosphor icons in `emoji-picker.tsx`, so this file stays a swappable data source).
 *
 * Each datum carries the glyph, a human `name` (shown in the preview and used as the
 * button's aria-label) and optional `keywords` (synonyms/shortcodes that broaden search
 * beyond the name). Categories follow the Unicode ordering used by every native picker.
 *
 * This is a curated, representative set, enough to feel complete and to exercise search,
 * sections, and pagination. Because the picker takes a `data` prop, a consumer can drop in
 * a fuller export (e.g. the full Unicode set) without touching the component.
 */

export interface EmojiDatum {
  /** The rendered glyph. */
  char: string
  /** Human name: preview label, button aria-label, and primary search target. */
  name: string
  /** Extra search terms beyond the name (synonyms, shortcodes). */
  keywords?: string[]
}

export interface EmojiCategory {
  /** Stable id: also the scroll anchor and nav key. */
  id: string
  /** Section header + nav tooltip label. */
  label: string
  emojis: EmojiDatum[]
}

export const emojiCategories: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys & Emotion",
    emojis: [
      { char: "😀", name: "Grinning face", keywords: ["happy", "smile"] },
      { char: "😃", name: "Grinning face with big eyes", keywords: ["happy"] },
      { char: "😄", name: "Grinning face with smiling eyes", keywords: ["happy"] },
      { char: "😁", name: "Beaming face with smiling eyes" },
      { char: "😆", name: "Grinning squinting face", keywords: ["laugh"] },
      { char: "😅", name: "Grinning face with sweat", keywords: ["relief"] },
      { char: "🤣", name: "Rolling on the floor laughing", keywords: ["rofl", "lol"] },
      { char: "😂", name: "Face with tears of joy", keywords: ["lol", "laugh", "cry"] },
      { char: "🙂", name: "Slightly smiling face" },
      { char: "🙃", name: "Upside-down face" },
      { char: "😉", name: "Winking face", keywords: ["wink"] },
      { char: "😊", name: "Smiling face with smiling eyes", keywords: ["blush"] },
      { char: "😇", name: "Smiling face with halo", keywords: ["angel"] },
      { char: "🥰", name: "Smiling face with hearts", keywords: ["love"] },
      { char: "😍", name: "Smiling face with heart-eyes", keywords: ["love", "crush"] },
      { char: "😘", name: "Face blowing a kiss", keywords: ["kiss", "love"] },
      { char: "😋", name: "Face savoring food", keywords: ["yum"] },
      { char: "😜", name: "Winking face with tongue", keywords: ["silly"] },
      { char: "🤪", name: "Zany face", keywords: ["crazy"] },
      { char: "🤩", name: "Star-struck", keywords: ["starstruck", "wow"] },
      { char: "😎", name: "Smiling face with sunglasses", keywords: ["cool"] },
      { char: "🥳", name: "Partying face", keywords: ["celebrate", "party"] },
      { char: "😏", name: "Smirking face", keywords: ["smug"] },
      { char: "🤔", name: "Thinking face", keywords: ["hmm"] },
      { char: "🤨", name: "Face with raised eyebrow", keywords: ["skeptical"] },
      { char: "😐", name: "Neutral face" },
      { char: "🙄", name: "Face with rolling eyes", keywords: ["eyeroll"] },
      { char: "😴", name: "Sleeping face", keywords: ["sleep", "zzz"] },
      { char: "😢", name: "Crying face", keywords: ["sad", "tear"] },
      { char: "😭", name: "Loudly crying face", keywords: ["sob", "sad"] },
      { char: "😤", name: "Face with steam from nose", keywords: ["angry", "triumph"] },
      { char: "😠", name: "Angry face", keywords: ["mad"] },
      { char: "😡", name: "Pouting face", keywords: ["rage", "angry"] },
      { char: "🤯", name: "Exploding head", keywords: ["mindblown"] },
      { char: "😱", name: "Face screaming in fear", keywords: ["scream", "shock"] },
      { char: "🥺", name: "Pleading face", keywords: ["puppy", "please"] },
      { char: "😬", name: "Grimacing face", keywords: ["awkward"] },
      { char: "🤗", name: "Hugging face", keywords: ["hug"] },
      { char: "🤫", name: "Shushing face", keywords: ["quiet", "shh"] },
      { char: "🤐", name: "Zipper-mouth face", keywords: ["secret"] },
      { char: "😷", name: "Face with medical mask", keywords: ["sick", "mask"] },
      { char: "🤒", name: "Face with thermometer", keywords: ["sick", "ill"] },
      { char: "🤮", name: "Face vomiting", keywords: ["sick", "puke"] },
      { char: "💀", name: "Skull", keywords: ["dead", "death"] },
      { char: "💩", name: "Pile of poo", keywords: ["poop"] },
      { char: "🤡", name: "Clown face" },
      { char: "👻", name: "Ghost", keywords: ["boo", "halloween"] },
      { char: "👽", name: "Alien", keywords: ["ufo"] },
      { char: "🤖", name: "Robot", keywords: ["bot"] },
    ],
  },
  {
    id: "people",
    label: "People & Body",
    emojis: [
      { char: "👋", name: "Waving hand", keywords: ["hi", "hello", "bye"] },
      { char: "🤚", name: "Raised back of hand" },
      { char: "✋", name: "Raised hand", keywords: ["stop", "high five"] },
      { char: "👌", name: "OK hand", keywords: ["okay", "perfect"] },
      { char: "🤌", name: "Pinched fingers", keywords: ["italian"] },
      { char: "✌️", name: "Victory hand", keywords: ["peace"] },
      { char: "🤞", name: "Crossed fingers", keywords: ["luck", "hope"] },
      { char: "🤟", name: "Love-you gesture" },
      { char: "🤘", name: "Sign of the horns", keywords: ["rock"] },
      { char: "🤙", name: "Call me hand", keywords: ["shaka"] },
      { char: "👈", name: "Backhand index pointing left" },
      { char: "👉", name: "Backhand index pointing right" },
      { char: "👆", name: "Backhand index pointing up" },
      { char: "👇", name: "Backhand index pointing down" },
      { char: "☝️", name: "Index pointing up" },
      { char: "👍", name: "Thumbs up", keywords: ["+1", "like", "yes", "approve"] },
      { char: "👎", name: "Thumbs down", keywords: ["-1", "dislike", "no"] },
      { char: "✊", name: "Raised fist", keywords: ["power"] },
      { char: "👊", name: "Oncoming fist", keywords: ["punch", "fist bump"] },
      { char: "👏", name: "Clapping hands", keywords: ["applause", "clap"] },
      { char: "🙌", name: "Raising hands", keywords: ["celebrate", "praise"] },
      { char: "👐", name: "Open hands" },
      { char: "🤝", name: "Handshake", keywords: ["deal", "agree"] },
      { char: "🙏", name: "Folded hands", keywords: ["please", "thanks", "pray"] },
      { char: "💪", name: "Flexed biceps", keywords: ["strong", "muscle"] },
      { char: "🫶", name: "Heart hands", keywords: ["love"] },
      { char: "👀", name: "Eyes", keywords: ["look", "watch"] },
      { char: "🧠", name: "Brain", keywords: ["smart"] },
      { char: "👶", name: "Baby" },
      { char: "🧑", name: "Person" },
      { char: "👨", name: "Man" },
      { char: "👩", name: "Woman" },
      { char: "🧓", name: "Older person" },
      { char: "👮", name: "Police officer" },
      { char: "🕵️", name: "Detective", keywords: ["spy"] },
      { char: "👷", name: "Construction worker" },
      { char: "🧑‍💻", name: "Technologist", keywords: ["developer", "coder"] },
      { char: "🦸", name: "Superhero" },
      { char: "🧙", name: "Mage", keywords: ["wizard"] },
      { char: "🧚", name: "Fairy" },
      { char: "👯", name: "People with bunny ears", keywords: ["dance"] },
      { char: "🚶", name: "Person walking" },
      { char: "🏃", name: "Person running", keywords: ["run"] },
    ],
  },
  {
    id: "animals",
    label: "Animals & Nature",
    emojis: [
      { char: "🐶", name: "Dog face", keywords: ["puppy"] },
      { char: "🐱", name: "Cat face", keywords: ["kitten"] },
      { char: "🐭", name: "Mouse face" },
      { char: "🐹", name: "Hamster" },
      { char: "🐰", name: "Rabbit face", keywords: ["bunny"] },
      { char: "🦊", name: "Fox" },
      { char: "🐻", name: "Bear" },
      { char: "🐼", name: "Panda" },
      { char: "🐨", name: "Koala" },
      { char: "🐯", name: "Tiger face" },
      { char: "🦁", name: "Lion" },
      { char: "🐮", name: "Cow face" },
      { char: "🐷", name: "Pig face" },
      { char: "🐸", name: "Frog" },
      { char: "🐵", name: "Monkey face" },
      { char: "🐔", name: "Chicken" },
      { char: "🐧", name: "Penguin" },
      { char: "🐦", name: "Bird" },
      { char: "🦅", name: "Eagle" },
      { char: "🦉", name: "Owl" },
      { char: "🦇", name: "Bat" },
      { char: "🐺", name: "Wolf" },
      { char: "🐗", name: "Boar" },
      { char: "🐴", name: "Horse face" },
      { char: "🦄", name: "Unicorn" },
      { char: "🐝", name: "Honeybee", keywords: ["bee"] },
      { char: "🐛", name: "Bug", keywords: ["caterpillar"] },
      { char: "🦋", name: "Butterfly" },
      { char: "🐌", name: "Snail" },
      { char: "🐞", name: "Lady beetle", keywords: ["ladybug"] },
      { char: "🐢", name: "Turtle" },
      { char: "🐍", name: "Snake" },
      { char: "🐙", name: "Octopus" },
      { char: "🦑", name: "Squid" },
      { char: "🦀", name: "Crab" },
      { char: "🐠", name: "Tropical fish", keywords: ["fish"] },
      { char: "🐬", name: "Dolphin" },
      { char: "🐳", name: "Spouting whale", keywords: ["whale"] },
      { char: "🦈", name: "Shark" },
      { char: "🌳", name: "Deciduous tree", keywords: ["tree"] },
      { char: "🌵", name: "Cactus" },
      { char: "🌻", name: "Sunflower" },
      { char: "🌹", name: "Rose", keywords: ["flower"] },
      { char: "🌸", name: "Cherry blossom", keywords: ["flower", "sakura"] },
      { char: "🍀", name: "Four leaf clover", keywords: ["luck"] },
      { char: "🌈", name: "Rainbow" },
      { char: "🔥", name: "Fire", keywords: ["lit", "hot", "flame"] },
      { char: "⭐", name: "Star" },
      { char: "🌙", name: "Crescent moon", keywords: ["night"] },
      { char: "☀️", name: "Sun", keywords: ["sunny"] },
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    emojis: [
      { char: "🍎", name: "Red apple", keywords: ["fruit"] },
      { char: "🍌", name: "Banana" },
      { char: "🍇", name: "Grapes" },
      { char: "🍓", name: "Strawberry" },
      { char: "🫐", name: "Blueberries" },
      { char: "🍒", name: "Cherries" },
      { char: "🍑", name: "Peach" },
      { char: "🍍", name: "Pineapple" },
      { char: "🥝", name: "Kiwi fruit" },
      { char: "🍅", name: "Tomato" },
      { char: "🥑", name: "Avocado" },
      { char: "🌽", name: "Ear of corn", keywords: ["corn"] },
      { char: "🥕", name: "Carrot" },
      { char: "🥦", name: "Broccoli" },
      { char: "🍞", name: "Bread" },
      { char: "🧀", name: "Cheese" },
      { char: "🍔", name: "Hamburger", keywords: ["burger"] },
      { char: "🍟", name: "French fries", keywords: ["fries"] },
      { char: "🍕", name: "Pizza" },
      { char: "🌭", name: "Hot dog" },
      { char: "🌮", name: "Taco" },
      { char: "🌯", name: "Burrito" },
      { char: "🍜", name: "Steaming bowl", keywords: ["ramen", "noodles"] },
      { char: "🍣", name: "Sushi" },
      { char: "🍤", name: "Fried shrimp" },
      { char: "🍙", name: "Rice ball" },
      { char: "🍦", name: "Soft ice cream", keywords: ["ice cream"] },
      { char: "🍩", name: "Doughnut", keywords: ["donut"] },
      { char: "🍪", name: "Cookie" },
      { char: "🎂", name: "Birthday cake", keywords: ["cake"] },
      { char: "🍰", name: "Shortcake", keywords: ["cake"] },
      { char: "🍫", name: "Chocolate bar", keywords: ["chocolate"] },
      { char: "🍬", name: "Candy" },
      { char: "🍿", name: "Popcorn" },
      { char: "☕", name: "Hot beverage", keywords: ["coffee", "tea"] },
      { char: "🍵", name: "Teacup without handle", keywords: ["tea"] },
      { char: "🧉", name: "Mate" },
      { char: "🍺", name: "Beer mug", keywords: ["beer"] },
      { char: "🍻", name: "Clinking beer mugs", keywords: ["cheers"] },
      { char: "🥂", name: "Clinking glasses", keywords: ["cheers", "champagne"] },
      { char: "🍷", name: "Wine glass", keywords: ["wine"] },
      { char: "🍸", name: "Cocktail glass", keywords: ["martini"] },
      { char: "🥤", name: "Cup with straw", keywords: ["soda"] },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    emojis: [
      { char: "⚽", name: "Soccer ball", keywords: ["football"] },
      { char: "🏀", name: "Basketball" },
      { char: "🏈", name: "American football" },
      { char: "⚾", name: "Baseball" },
      { char: "🎾", name: "Tennis" },
      { char: "🏐", name: "Volleyball" },
      { char: "🏉", name: "Rugby football" },
      { char: "🎱", name: "Pool 8 ball", keywords: ["billiards"] },
      { char: "🏓", name: "Ping pong", keywords: ["table tennis"] },
      { char: "🏸", name: "Badminton" },
      { char: "🥅", name: "Goal net" },
      { char: "⛳", name: "Flag in hole", keywords: ["golf"] },
      { char: "🏹", name: "Bow and arrow", keywords: ["archery"] },
      { char: "🎣", name: "Fishing pole" },
      { char: "🥊", name: "Boxing glove" },
      { char: "🥋", name: "Martial arts uniform" },
      { char: "🎽", name: "Running shirt" },
      { char: "🛹", name: "Skateboard" },
      { char: "🛼", name: "Roller skate" },
      { char: "⛸️", name: "Ice skate" },
      { char: "🎿", name: "Skis" },
      { char: "🏂", name: "Snowboarder" },
      { char: "🏋️", name: "Person lifting weights", keywords: ["gym", "workout"] },
      { char: "🤸", name: "Person cartwheeling" },
      { char: "🤼", name: "People wrestling" },
      { char: "🏆", name: "Trophy", keywords: ["win", "champion"] },
      { char: "🥇", name: "1st place medal", keywords: ["gold"] },
      { char: "🥈", name: "2nd place medal", keywords: ["silver"] },
      { char: "🥉", name: "3rd place medal", keywords: ["bronze"] },
      { char: "🏅", name: "Sports medal" },
      { char: "🎖️", name: "Military medal" },
      { char: "🎯", name: "Direct hit", keywords: ["target", "bullseye"] },
      { char: "🎲", name: "Game die", keywords: ["dice"] },
      { char: "🎮", name: "Video game", keywords: ["controller", "gaming"] },
      { char: "🎰", name: "Slot machine" },
      { char: "🎳", name: "Bowling" },
      { char: "🎭", name: "Performing arts", keywords: ["theater"] },
      { char: "🎨", name: "Artist palette", keywords: ["art", "paint"] },
      { char: "🎤", name: "Microphone", keywords: ["sing", "karaoke"] },
      { char: "🎧", name: "Headphone", keywords: ["music"] },
      { char: "🎸", name: "Guitar" },
      { char: "🎹", name: "Musical keyboard", keywords: ["piano"] },
      { char: "🥁", name: "Drum" },
      { char: "🎺", name: "Trumpet" },
      { char: "🎉", name: "Party popper", keywords: ["celebrate", "tada"] },
      { char: "🎊", name: "Confetti ball", keywords: ["celebrate"] },
      { char: "🎈", name: "Balloon" },
      { char: "🎁", name: "Wrapped gift", keywords: ["present"] },
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    emojis: [
      { char: "🚗", name: "Automobile", keywords: ["car"] },
      { char: "🚕", name: "Taxi" },
      { char: "🚌", name: "Bus" },
      { char: "🏎️", name: "Racing car" },
      { char: "🚓", name: "Police car" },
      { char: "🚑", name: "Ambulance" },
      { char: "🚒", name: "Fire engine" },
      { char: "🚜", name: "Tractor" },
      { char: "🛵", name: "Motor scooter" },
      { char: "🏍️", name: "Motorcycle" },
      { char: "🚲", name: "Bicycle", keywords: ["bike"] },
      { char: "✈️", name: "Airplane", keywords: ["flight", "travel"] },
      { char: "🚀", name: "Rocket", keywords: ["launch", "space"] },
      { char: "🛸", name: "Flying saucer", keywords: ["ufo"] },
      { char: "🚁", name: "Helicopter" },
      { char: "⛵", name: "Sailboat" },
      { char: "🚤", name: "Speedboat" },
      { char: "🛳️", name: "Passenger ship", keywords: ["cruise"] },
      { char: "🚂", name: "Locomotive", keywords: ["train"] },
      { char: "🚆", name: "Train" },
      { char: "🚇", name: "Metro", keywords: ["subway"] },
      { char: "🗺️", name: "World map", keywords: ["travel"] },
      { char: "🧭", name: "Compass" },
      { char: "🏔️", name: "Snow-capped mountain", keywords: ["mountain"] },
      { char: "🌋", name: "Volcano" },
      { char: "🏕️", name: "Camping" },
      { char: "🏖️", name: "Beach with umbrella", keywords: ["beach"] },
      { char: "🏝️", name: "Desert island", keywords: ["island"] },
      { char: "🗽", name: "Statue of Liberty" },
      { char: "🗼", name: "Tokyo tower" },
      { char: "🏰", name: "Castle" },
      { char: "🏯", name: "Japanese castle" },
      { char: "🎡", name: "Ferris wheel" },
      { char: "🎢", name: "Roller coaster" },
      { char: "🎪", name: "Circus tent" },
      { char: "🏠", name: "House", keywords: ["home"] },
      { char: "🏢", name: "Office building" },
      { char: "🏥", name: "Hospital" },
      { char: "🏦", name: "Bank" },
      { char: "🏨", name: "Hotel" },
      { char: "🏫", name: "School" },
      { char: "⛲", name: "Fountain" },
      { char: "🌉", name: "Bridge at night", keywords: ["bridge"] },
      { char: "🗿", name: "Moai", keywords: ["statue"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    emojis: [
      { char: "⌚", name: "Watch" },
      { char: "📱", name: "Mobile phone", keywords: ["phone"] },
      { char: "💻", name: "Laptop", keywords: ["computer"] },
      { char: "🖥️", name: "Desktop computer" },
      { char: "🖨️", name: "Printer" },
      { char: "⌨️", name: "Keyboard" },
      { char: "🖱️", name: "Computer mouse" },
      { char: "💾", name: "Floppy disk", keywords: ["save"] },
      { char: "💿", name: "Optical disk", keywords: ["cd"] },
      { char: "📷", name: "Camera" },
      { char: "📸", name: "Camera with flash" },
      { char: "🎥", name: "Movie camera" },
      { char: "📺", name: "Television", keywords: ["tv"] },
      { char: "📻", name: "Radio" },
      { char: "🔋", name: "Battery" },
      { char: "🔌", name: "Electric plug", keywords: ["power"] },
      { char: "💡", name: "Light bulb", keywords: ["idea"] },
      { char: "🔦", name: "Flashlight" },
      { char: "🕯️", name: "Candle" },
      { char: "📖", name: "Open book", keywords: ["read"] },
      { char: "📚", name: "Books" },
      { char: "📝", name: "Memo", keywords: ["note", "write"] },
      { char: "✏️", name: "Pencil" },
      { char: "🖊️", name: "Pen" },
      { char: "📌", name: "Pushpin", keywords: ["pin"] },
      { char: "📎", name: "Paperclip" },
      { char: "✂️", name: "Scissors", keywords: ["cut"] },
      { char: "📁", name: "File folder", keywords: ["folder"] },
      { char: "📅", name: "Calendar", keywords: ["date"] },
      { char: "📈", name: "Chart increasing", keywords: ["growth", "stats"] },
      { char: "📉", name: "Chart decreasing" },
      { char: "💰", name: "Money bag", keywords: ["money"] },
      { char: "💳", name: "Credit card" },
      { char: "💎", name: "Gem stone", keywords: ["diamond"] },
      { char: "🔑", name: "Key" },
      { char: "🔒", name: "Locked", keywords: ["lock", "secure"] },
      { char: "🔓", name: "Unlocked" },
      { char: "🔨", name: "Hammer", keywords: ["tool"] },
      { char: "🔧", name: "Wrench", keywords: ["tool", "fix"] },
      { char: "⚙️", name: "Gear", keywords: ["settings"] },
      { char: "🧲", name: "Magnet" },
      { char: "🧪", name: "Test tube", keywords: ["science", "lab"] },
      { char: "🔬", name: "Microscope" },
      { char: "🔭", name: "Telescope" },
      { char: "💊", name: "Pill", keywords: ["medicine"] },
      { char: "🩹", name: "Adhesive bandage", keywords: ["bandaid"] },
      { char: "🧰", name: "Toolbox" },
      { char: "🛒", name: "Shopping cart", keywords: ["cart"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    emojis: [
      { char: "❤️", name: "Red heart", keywords: ["love"] },
      { char: "🧡", name: "Orange heart" },
      { char: "💛", name: "Yellow heart" },
      { char: "💚", name: "Green heart" },
      { char: "💙", name: "Blue heart" },
      { char: "💜", name: "Purple heart" },
      { char: "🖤", name: "Black heart" },
      { char: "🤍", name: "White heart" },
      { char: "🤎", name: "Brown heart" },
      { char: "💔", name: "Broken heart" },
      { char: "❣️", name: "Heart exclamation" },
      { char: "💕", name: "Two hearts", keywords: ["love"] },
      { char: "💞", name: "Revolving hearts" },
      { char: "💗", name: "Growing heart" },
      { char: "💖", name: "Sparkling heart" },
      { char: "💘", name: "Heart with arrow", keywords: ["cupid"] },
      { char: "💝", name: "Heart with ribbon" },
      { char: "💯", name: "Hundred points", keywords: ["100", "perfect"] },
      { char: "✅", name: "Check mark button", keywords: ["check", "done", "yes"] },
      { char: "❌", name: "Cross mark", keywords: ["x", "no", "wrong"] },
      { char: "❗", name: "Exclamation mark", keywords: ["warning"] },
      { char: "❓", name: "Question mark", keywords: ["help"] },
      { char: "⚠️", name: "Warning", keywords: ["caution"] },
      { char: "🚫", name: "Prohibited", keywords: ["no", "forbidden"] },
      { char: "♻️", name: "Recycling symbol", keywords: ["recycle"] },
      { char: "✨", name: "Sparkles", keywords: ["shiny", "magic"] },
      { char: "⭐", name: "Star" },
      { char: "🌟", name: "Glowing star" },
      { char: "💫", name: "Dizzy", keywords: ["stars"] },
      { char: "⚡", name: "High voltage", keywords: ["lightning", "bolt"] },
      { char: "💥", name: "Collision", keywords: ["boom"] },
      { char: "💢", name: "Anger symbol" },
      { char: "💬", name: "Speech balloon", keywords: ["chat", "comment"] },
      { char: "💭", name: "Thought balloon" },
      { char: "🔔", name: "Bell", keywords: ["notification"] },
      { char: "🔕", name: "Bell with slash", keywords: ["mute"] },
      { char: "🎵", name: "Musical note", keywords: ["music"] },
      { char: "🎶", name: "Musical notes" },
      { char: "➕", name: "Plus" },
      { char: "➖", name: "Minus" },
      { char: "✖️", name: "Multiply" },
      { char: "➗", name: "Divide" },
      { char: "♾️", name: "Infinity" },
      { char: "🔗", name: "Link" },
      { char: "💲", name: "Heavy dollar sign", keywords: ["money"] },
      { char: "🆗", name: "OK button", keywords: ["okay"] },
      { char: "🆕", name: "New button" },
      { char: "🔝", name: "Top arrow", keywords: ["up"] },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    emojis: [
      { char: "🏁", name: "Chequered flag", keywords: ["race", "finish"] },
      { char: "🚩", name: "Triangular flag" },
      { char: "🏴", name: "Black flag" },
      { char: "🏳️", name: "White flag", keywords: ["surrender"] },
      { char: "🏳️‍🌈", name: "Rainbow flag", keywords: ["pride", "lgbt"] },
      { char: "🏴‍☠️", name: "Pirate flag" },
      { char: "🇺🇸", name: "United States", keywords: ["usa", "america"] },
      { char: "🇬🇧", name: "United Kingdom", keywords: ["uk", "britain"] },
      { char: "🇪🇸", name: "Spain", keywords: ["españa"] },
      { char: "🇫🇷", name: "France" },
      { char: "🇩🇪", name: "Germany" },
      { char: "🇮🇹", name: "Italy" },
      { char: "🇵🇹", name: "Portugal" },
      { char: "🇳🇱", name: "Netherlands" },
      { char: "🇧🇪", name: "Belgium" },
      { char: "🇨🇭", name: "Switzerland" },
      { char: "🇸🇪", name: "Sweden" },
      { char: "🇳🇴", name: "Norway" },
      { char: "🇩🇰", name: "Denmark" },
      { char: "🇫🇮", name: "Finland" },
      { char: "🇮🇪", name: "Ireland" },
      { char: "🇵🇱", name: "Poland" },
      { char: "🇺🇦", name: "Ukraine" },
      { char: "🇷🇺", name: "Russia" },
      { char: "🇹🇷", name: "Turkey" },
      { char: "🇬🇷", name: "Greece" },
      { char: "🇨🇦", name: "Canada" },
      { char: "🇲🇽", name: "Mexico" },
      { char: "🇧🇷", name: "Brazil" },
      { char: "🇦🇷", name: "Argentina" },
      { char: "🇨🇱", name: "Chile" },
      { char: "🇨🇴", name: "Colombia" },
      { char: "🇯🇵", name: "Japan" },
      { char: "🇰🇷", name: "South Korea" },
      { char: "🇨🇳", name: "China" },
      { char: "🇮🇳", name: "India" },
      { char: "🇦🇺", name: "Australia" },
      { char: "🇳🇿", name: "New Zealand" },
      { char: "🇿🇦", name: "South Africa" },
      { char: "🇪🇬", name: "Egypt" },
      { char: "🇳🇬", name: "Nigeria" },
      { char: "🇸🇦", name: "Saudi Arabia" },
    ],
  },
]

/**
 * Default "frequently used" presets: the quick-reaction row pinned above the categories.
 * Override per call site via the `presets` prop.
 */
export const defaultEmojiPresets: string[] = [
  "👍",
  "❤️",
  "😂",
  "🎉",
  "😍",
  "🙏",
  "🔥",
  "😢",
]

/** Flat char → datum index, for resolving recents/presets back to names + keywords. */
export const emojiIndex: Map<string, EmojiDatum> = new Map(
  emojiCategories.flatMap((category) => category.emojis.map((e) => [e.char, e] as const)),
)
