export {
  PromoCard,
  PromoCardContent,
  PromoCardEyebrow,
  PromoCardIcon,
  PromoCardTitle,
  PromoCardDescription,
  PromoCardActions,
  PromoCardMedia,
  PromoCardClose,
  promoCardVariants,
  type PromoCardProps,
  type PromoCardActionsProps,
  type PromoCardCloseProps,
} from "./promo-card"
