export {
  Footer,
  FooterTop,
  FooterBrand,
  FooterTagline,
  FooterColumns,
  FooterColumn,
  FooterLink,
  FooterSocial,
  FooterSocialLink,
  FooterBottom,
  FooterCopyright,
  FooterLegal,
  footerVariants,
  type FooterProps,
  type FooterColumnProps,
  type FooterLinkProps,
  type FooterSocialLinkProps,
} from "./footer"
