export {
  FileCard,
  FileCardIcon,
  FileCardThumbnail,
  FileCardContent,
  FileCardName,
  FileCardMeta,
  FileCardValue,
  FileCardActions,
  FileCardProgress,
  FileCardStatus,
  fileCardVariants,
  fileTypeFromName,
  type FileCardProps,
  type FileCardIconProps,
  type FileCardThumbnailProps,
  type FileCardProgressProps,
  type FileCardStatusProps,
  type FileCardType,
} from "./file-card"
