import {
  House,
  DownloadSimple,
  Stack,
  Compass,
  Palette,
  TextAa,
  Ruler,
  Rows,
  BoundingBox,
  Wind,
  Shapes,
  UserCircle,
  Tag,
  TagChevron,
  Path,
  CursorClick,
  SquaresFour,
  Cards,
  CheckSquare,
  CodeBlock,
  AppWindow,
  ListDashes,
  Tray,
  CaretUpDown,
  Browsers,
  Table as TableIcon,
  ChatTeardrop,
  BellSimple,
  Textbox,
  LinkSimple as LinkIcon,
  IdentificationCard,
  Password,
  ShieldCheck,
  Pulse,
  Warning,
  Devices,
  Keyboard,
  CaretCircleDown,
  ListNumbers,
  ListChecks,
  PencilSimpleLine,
  PlayCircle,
  TextT,
  Slideshow,
  SidebarSimple,
  Sidebar as SidebarIcon,
  ToggleRight,
  Steps,
  CalendarDots,
  Signpost,
  Flag,
  Quotes,
  SquareHalfBottom,
  Smiley,
  PictureInPicture,
  RadioButton,
  TextAlignLeft,
  Sliders,
  Minus,
  SquareHalf,
  Swatches,
  ToggleLeft,
  Eyedropper,
  ChartLineUp,
  ChartBar,
  Gauge,
  Fingerprint,
  EnvelopeSimple,
  ChatCenteredDots,
  PaperPlaneTilt,
  CreditCard,
  UserGear,
  UsersThree,
  Ranking as RankingIcon,
  Receipt,
  FileArrowUp,
  UploadSimple,
  TreeView,
  ClockCounterClockwise,
  Command as CommandIcon,
  ListBullets,
  List as ListIcon,
  ClipboardText,
  Star,
  Sparkle,
  Cookie,
  Columns,
  ChatCircleDots,
  Robot,
  MagicWand,
  Megaphone,
  QrCode,
  Images,
  GridFour,
  FrameCorners,
  Article,
  CurrencyDollar,
  Question,
  Newspaper,
  MouseRightClick,
  ArrowsDownUp,
  SealCheck,
  Stamp,
  Toolbox,
} from "@phosphor-icons/react/ssr"
// NOTE: PRO marketing sections/pages live in the private koala-ui-pro repo and are
// not part of this public docs nav. See registry.json (tier: "pro").
import type { Icon } from "@phosphor-icons/react"

/**
 * Docs navigation tree: single source of truth for the sidebar and (later) for
 * "previous/next" links. Add a component by dropping an entry under "Components"
 * and creating the matching `app/docs/...` route.
 */
export interface NavItem {
  title: string
  href: string
  /** Phosphor icon rendered before the label in the sidebar. */
  icon: Icon
  /** Marks work-in-progress entries with a muted "Soon" badge. */
  soon?: boolean
}

export interface NavSection {
  title: string
  items: NavItem[]
}

export const docsNav: NavSection[] = [
  {
    title: "Getting Started",
    items: [
      { title: "Introduction", href: "/docs", icon: House },
      { title: "Installation", href: "/docs/installation", icon: DownloadSimple },
      { title: "Components", href: "/docs/components", icon: SquaresFour },
      { title: "Architecture", href: "/docs/architecture", icon: Stack },
      { title: "Patterns", href: "/docs/patterns", icon: Compass },
    ],
  },
  {
    title: "Foundations",
    items: [
      { title: "Theming", href: "/docs/foundations/theming", icon: Swatches },
      { title: "Colors", href: "/docs/foundations/colors", icon: Palette },
      { title: "Typography", href: "/docs/foundations/typography", icon: TextAa },
      { title: "Spacing & Layout", href: "/docs/foundations/spacing", icon: Ruler },
      { title: "Breakpoints", href: "/docs/foundations/breakpoints", icon: Devices },
      { title: "Density", href: "/docs/foundations/density", icon: Rows },
      { title: "Radius & Shadows", href: "/docs/foundations/surfaces", icon: BoundingBox },
      { title: "Motion", href: "/docs/foundations/motion", icon: Wind },
      { title: "Fade", href: "/docs/foundations/scroll-fade", icon: ArrowsDownUp },
      { title: "Icons", href: "/docs/foundations/icons", icon: Shapes },
      { title: "Logos", href: "/docs/logos", icon: Stamp },
    ],
  },
  {
    title: "AI",
    items: [
      { title: "AI Panel", href: "/docs/components/ai-panel", icon: Robot },
      { title: "Chat", href: "/docs/components/chat", icon: ChatCircleDots },
      { title: "Prompt Input", href: "/docs/components/prompt-input", icon: Sparkle },
      { title: "Suggestions", href: "/docs/components/suggestions", icon: MagicWand },
    ],
  },
  {
    // The new sections tier (organism slabs with a device-frame preview). Greenfield alongside
    // the component-level "Marketing" group below; the components graduate here over time. See
    // memory `site-ia-tiers`.
    title: "Marketing / Sections",
    // One entry per family, in landing-page reading order. Each family page stacks its numbered
    // variants (Variant 1, Variant 2…) as labeled device-frame previews, Flowbase-style (see memory
    // `site-ia-tiers`). Page chrome (Banner, Footer, Navbar) keeps its own family at the end.
    items: [
      { title: "Hero", href: "/marketing/sections/hero", icon: Flag },
      { title: "Social Proof", href: "/marketing/sections/social-proof", icon: SealCheck },
      { title: "Feature", href: "/marketing/sections/feature", icon: SquaresFour },
      { title: "Gallery", href: "/marketing/sections/gallery", icon: Images },
      { title: "Testimonials", href: "/marketing/sections/testimonials", icon: Quotes },
      { title: "Stats", href: "/marketing/sections/stats", icon: ChartBar },
      { title: "Pricing", href: "/marketing/sections/pricing", icon: CurrencyDollar },
      { title: "FAQ", href: "/marketing/sections/faq", icon: Question },
      { title: "Changelog", href: "/marketing/sections/changelog", icon: ClockCounterClockwise },
      { title: "Blog", href: "/marketing/sections/blog", icon: Newspaper },
      { title: "CTA", href: "/marketing/sections/cta", icon: PaperPlaneTilt },
      { title: "Contact", href: "/marketing/sections/contact", icon: EnvelopeSimple },
      { title: "Banner", href: "/marketing/sections/banner", icon: Megaphone },
      { title: "Footer", href: "/marketing/sections/footer", icon: SquareHalfBottom },
      { title: "Navbar", href: "/marketing/sections/navbar", icon: Signpost },
    ],
  },
  {
    // The page tier of the marketing domain (see memory `site-ia-tiers`): several sections stacked
    // into a finished screen, previewed top-to-bottom in the same device frame. Blog post is the
    // first family; landing, about, and pricing pages graduate here over time.
    title: "Marketing / Pages",
    items: [
      { title: "Blog post", href: "/marketing/pages/blog-post", icon: Article },
    ],
  },
  {
    // The application-domain sibling of "Marketing / Sections": full app SCREENS (page tier) with
    // the same device-frame preview. Auth is the first family; settings, dashboards, and empty
    // states graduate here over time. See memory `site-ia-tiers`.
    title: "App / Sections",
    items: [
      { title: "Authentication", href: "/app/sections/authentication", icon: Fingerprint },
      { title: "Checkout", href: "/app/sections/checkout", icon: CreditCard },
    ],
  },
  {
    title: "Marketing",
    items: [
      { title: "Banner", href: "/docs/components/banner", icon: Megaphone },
      { title: "Bento", href: "/docs/components/bento", icon: GridFour },
      { title: "FAQs", href: "/docs/components/faqs", icon: Question },
      { title: "Footer", href: "/docs/components/footer", icon: SquareHalfBottom },
      { title: "Gallery", href: "/docs/components/gallery", icon: Images },
      { title: "Hero", href: "/docs/components/hero", icon: Flag },
      { title: "Navbar", href: "/docs/components/navbar", icon: Signpost },
      { title: "Pricing", href: "/docs/components/pricing", icon: CurrencyDollar },
      { title: "Pricing Comparison", href: "/docs/components/pricing-comparison", icon: TableIcon },
      { title: "Section", href: "/docs/components/section", icon: Rows },
      { title: "Section Header", href: "/docs/components/section-header", icon: Article },
      { title: "Testimonials", href: "/docs/components/testimonials", icon: Quotes },
    ],
  },
  {
    title: "Forms",
    items: [
      { title: "Authentication", href: "/docs/components/auth-form", icon: Fingerprint },
      { title: "Contact", href: "/docs/components/contact-form", icon: EnvelopeSimple },
      { title: "Feedback", href: "/docs/components/feedback-form", icon: ChatCenteredDots },
      { title: "Newsletter", href: "/docs/components/newsletter-form", icon: PaperPlaneTilt },
      { title: "Payment", href: "/docs/components/payment-form", icon: CreditCard },
      { title: "Settings", href: "/docs/components/settings-form", icon: UserGear },
      { title: "Survey", href: "/docs/components/survey", icon: ClipboardText },
      { title: "Waitlist", href: "/docs/components/waitlist-form", icon: UsersThree },
    ],
  },
  {
    title: "Data Display",
    items: [
      { title: "Animated Number", href: "/docs/components/animated-number", icon: Gauge },
      { title: "Chart", href: "/docs/components/chart", icon: ChartBar },
      { title: "Data Table", href: "/docs/components/data-table", icon: TableIcon },
      { title: "Description List", href: "/docs/components/description-list", icon: ListBullets },
      { title: "Order Summary", href: "/docs/components/order-summary", icon: Receipt },
      { title: "Ranking", href: "/docs/components/ranking", icon: RankingIcon },
      { title: "Stat", href: "/docs/components/stat", icon: ChartLineUp },
    ],
  },
  {
    title: "Product",
    items: [
      { title: "Accordion", href: "/docs/components/accordion", icon: CaretCircleDown },
      { title: "Activity Feed", href: "/docs/components/activity-feed", icon: ClockCounterClockwise },
      { title: "Alert", href: "/docs/components/alert", icon: Warning },
      { title: "Avatar", href: "/docs/components/avatar", icon: UserCircle },
      { title: "Avatar Group", href: "/docs/components/avatar-group", icon: UsersThree },
      { title: "Badge", href: "/docs/components/badge", icon: Tag },
      { title: "Badge Group", href: "/docs/components/badge-group", icon: TagChevron },
      { title: "Breadcrumb", href: "/docs/components/breadcrumb", icon: Path },
      { title: "Button", href: "/docs/components/button", icon: CursorClick },
      { title: "Button Group", href: "/docs/components/button-group", icon: SquaresFour },
      { title: "Card", href: "/docs/components/card", icon: Cards },
      { title: "Carousel", href: "/docs/components/carousel", icon: Slideshow },
      { title: "Checkbox", href: "/docs/components/checkbox", icon: CheckSquare },
      { title: "Code Snippet", href: "/docs/components/code-snippet", icon: CodeBlock },
      { title: "Color Picker", href: "/docs/components/color-picker", icon: Eyedropper },
      { title: "Command", href: "/docs/components/command", icon: CommandIcon },
      { title: "Context Menu", href: "/docs/components/context-menu", icon: MouseRightClick },
      { title: "Cookie Consent", href: "/docs/components/cookie-consent", icon: Cookie },
      { title: "Date Picker", href: "/docs/components/date-picker", icon: CalendarDots },
      { title: "Dialog", href: "/docs/components/dialog", icon: AppWindow },
      { title: "Divider", href: "/docs/components/divider", icon: Minus },
      { title: "Drawer", href: "/docs/components/drawer", icon: SquareHalf },
      { title: "Dropdown Menu", href: "/docs/components/dropdown-menu", icon: ListDashes },
      { title: "Emoji Picker", href: "/docs/components/emoji-picker", icon: Smiley },
      { title: "Empty State", href: "/docs/components/empty-state", icon: Tray },
      { title: "Field", href: "/docs/components/field", icon: IdentificationCard },
      { title: "File Card", href: "/docs/components/file-card", icon: FileArrowUp },
      { title: "File Upload", href: "/docs/components/file-upload", icon: UploadSimple },
      { title: "Input", href: "/docs/components/input", icon: Textbox },
      { title: "Input Group", href: "/docs/components/input-group", icon: Columns },
      { title: "Kbd", href: "/docs/components/kbd", icon: Keyboard },
      { title: "Label", href: "/docs/components/label", icon: TextT },
      { title: "Layout", href: "/docs/components/layout", icon: SidebarIcon },
      { title: "Link", href: "/docs/components/link", icon: LinkIcon },
      { title: "Lightbox", href: "/docs/components/lightbox", icon: FrameCorners },
      { title: "List", href: "/docs/components/list", icon: ListIcon },
      { title: "Multi Select", href: "/docs/components/multi-select", icon: ListChecks },
      { title: "OTP Input", href: "/docs/components/otp-input", icon: Password },
      { title: "Pagination", href: "/docs/components/pagination", icon: ListNumbers },
      { title: "Password Strength", href: "/docs/components/password-strength", icon: ShieldCheck },
      { title: "Popover", href: "/docs/components/popover", icon: PictureInPicture },
      { title: "QR Code", href: "/docs/components/qr-code", icon: QrCode },
      { title: "Radio Group", href: "/docs/components/radio-group", icon: RadioButton },
      { title: "Rating", href: "/docs/components/rating", icon: Star },
      { title: "Resizable", href: "/docs/components/resizable", icon: Columns },
      { title: "Rich Text Editor", href: "/docs/components/rich-text-editor", icon: PencilSimpleLine },
      { title: "Select", href: "/docs/components/select", icon: CaretUpDown },
      { title: "Sidebar", href: "/docs/components/sidebar", icon: SidebarSimple },
      { title: "Skeleton", href: "/docs/components/skeleton", icon: Pulse },
      { title: "Slider", href: "/docs/components/slider", icon: Sliders },
      { title: "Stepper", href: "/docs/components/stepper", icon: Steps },
      { title: "Switch", href: "/docs/components/switch", icon: ToggleRight },
      { title: "Tabs", href: "/docs/components/tabs", icon: Browsers },
      { title: "Textarea", href: "/docs/components/textarea", icon: TextAlignLeft },
      { title: "Toast", href: "/docs/components/toast", icon: BellSimple },
      { title: "Toggle Group", href: "/docs/components/toggle-group", icon: ToggleLeft },
      { title: "Toolbar", href: "/docs/components/toolbar", icon: Toolbox },
      { title: "Tooltip", href: "/docs/components/tooltip", icon: ChatTeardrop },
      { title: "Tree", href: "/docs/components/tree", icon: TreeView },
      { title: "Video Player", href: "/docs/components/video-player", icon: PlayCircle },
    ],
  },
]
